FROM nginx:1.23.3

ADD https://raw.githubusercontent.com/ViniciusPilan/aws-project/main/server/html/* /usr/share/nginx/html
ADD https://raw.githubusercontent.com/ViniciusPilan/aws-project/main/server/conf.d/* /etc/nginx/conf.d
